### ISSUE TITLE
BUG: Grenade range is not accurate

### ISSUE THREAD

**Issue by emlos** [bparc/rogue#12]
Sometimes, if the player is adjacent ot the grenade range, but _not_ inside it, they get damaged in the blast too. See in action on the video: https://github.com/user-attachments/assets/92944c6b-e2b7-4a0d-baeb-db819c3b9f90

**Comment by bparc** [comment]
This is most likely due to an inconsistency between a "range" value used to display the \*visuals\* of an effective range, and a "range" value used to determine if an entity is within a blast radius.
This issue will get resolved when we'll have a more well-defined data format for action types.

**Comment by michalw00** [comment]
Possibly fixed
