### ISSUE TITLE
Let's make a menu for character abilities!

### ISSUE THREAD

**Issue by bparc** [bparc/rogue#3]
We're about to add a bunch of “character skills/abilities” for placing traps around the map, inflicting status effects and pushing enemies all over the place. Hence, it's pretty safe to assume that we'll need some way of interfacing with them!
For starters, I suggest binding one gamepad button to a ‘default attack’, and a second one to some sort of skill menu. On KB/M those buttons could be mapped to LMB and RMB respectively.
Furthermore, we'll need some kind of ‘list-of-enemies-in-effective-range’ menu to make targeting enemies around the player *flow* better!
The menu doesn't have to look *too* nice for now. Let's focus on the practical aspect of it.

**Comment by emlos** [comment]
i like the mapping-rmb-to-default-attack part! in my "concept art" i imagined an in-combat menu at the bottom middle of the screen (kinda like a sideways turn queue), where the player can choose the ability/special attack either with mouse, if we want to support mouse at all, or via hotkeys. 
I cant imagine we'd let the player have more then 9 active abilities at any time (maybe they can choose which skills to have equipped out of combat?), so we could map the abilities to the numbers 1-9 or something.
