### ISSUE TITLE
Let's restructure the “environmental trap” system!

### ISSUE THREAD

**Issue by bparc** [bparc/rogue#4]
As of now, there is not one, but *two* systems for handling “environmental traps” in the code-base!
We could either get rid of one of them to reduce the overall complexity of the system OR leave them both be.
But, before making that decision, it would be nice to really narrow down on the thing that each of those two systems is trying to accomplish. Have a good idea of what kind of gameplay mechanics they would need to implement and what's the *actual* difference between them.
If anyone has *any* input on this matter, please write it in the comments!

**Comment by bparc** [comment]
Allright, here's my personal take on this: let's "unify" those two systems into one.
We will store 'traps' in a tile map (just like michalw00 did) for rendering and fast array lookups.
BUT. If we ever feel the need to have some kind of "time-based event" (say, a mine that explodes after some amount of turns passes), we will register that trap into the “static entity list”.
Each entry in that list will then only store a reference to its 'trap tile' and a “counter”, so that we'll be able to check whether the trap has already been triggered. But the *rendering* and spatial lookups will still be done via the tile map.

**Comment by emlos** [comment]
arguably, the traps "work" now, but we have not added any kind of turn based trap, which deserves it's own story.
