### ISSUE TITLE
hotbar assets + icons

### ISSUE THREAD

**Issue by emlos** [bparc/rogue#7]
We need:

- [x] hotbar whole image (530x60)
- [x] hotbar slices for dynamic slots building
Ability icons:
- [x] base melee attack
- [x] base ranged attack
- [x] grenade throw icon
- [x] base heal
- [x] push enemy

for any additions please comment them to the story

**Comment by michalw00** [comment]
We could use a "push enemy" action icon as well

**Comment by michalw00** [comment]
also a generic "heal" icon
